packages: []

catalogs:
  build:
    '@unocss/preset-web-fonts': ^66.1.4
    '@vitejs/plugin-vue': ^5.2.4
    unocss: ^66.1.4
    vite: ^6.3.5
  dev:
    '@antfu/eslint-config': ^4.14.1
    eslint: ^9.28.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.1.0
    pnpm: ^10.12.1
    simple-git: ^3.28.0
    simple-git-hooks: ^2.13.0
    tsx: ^4.19.4
    typescript: ~5.8.3
  frontend:
    vue: ^3.5.17
    vue-router: ^4.5.1
    vue-router-better-scroller: ^0.0.0
  types:
    '@types/node': ^22.15.30
