packages: []

catalogs:
  build:
    '@unocss/preset-web-fonts': ^66.1.4
    '@vitejs/plugin-vue': ^5.2.4
    gray-matter: ^4.0.3
    unocss: ^66.1.4
    unplugin-vue-router: ^0.12.0
    vite: ^6.3.5
    vite-ssg: ^27.0.1
  dev:
    '@antfu/eslint-config': ^4.14.1
    cross-env: ^7.0.3
    degit: ^2.8.4
    eslint: ^9.28.0
    eslint-plugin-format: ^1.0.1
    fs-extra: ^11.3.0
    lint-staged: ^16.1.0
    pnpm: ^10.12.1
    rimraf: ^6.0.1
    simple-git: ^3.28.0
    simple-git-hooks: ^2.13.0
    tsx: ^4.19.4
    typescript: ~5.8.3
  frontend:
    '@unocss/reset': ^66.1.4
    '@vueuse/core': ^13.4.0
    pinia: ^3.0.3
    vue: ^3.5.17
    vue-router: ^4.5.1
    vue-router-better-scroller: ^0.0.0
  types:
    '@types/degit': ^2.8.6
    '@types/fs-extra': ^11.0.4
    '@types/node': ^22.15.30
